version: 2.1
build_common: &build_common
  steps:
    - checkout
    - run:
        name: Install Dependencies
        command: sudo pip3 install --requirement requirements.txt
    - run:
        name: Build Package
        command: python3 setup.py sdist bdist_wheel
    - run:
        name: Run Tests
        command: |
            coverage run -m unittest --verbose
            coveralls
    - run:
        name: Check Types - Pyre
        command: pyre check
    - run:
        name: Check Types - Mypy
        command: mypy .
    - run:
        name: Check Lint - Flake8
        command: flake8
    - run:
        name: Check Format - Black
        command: black --check .
jobs:
  python36:
    docker:
      - image: circleci/python:3.6
    <<: *build_common
  python37:
    docker:
      - image: circleci/python:3.7
      <<: *build_common
workflows:
  version: 2
  build:
    jobs:
      - python36
      - python37
      - python38