version: 2.1
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo pip3 install --requirement requirements.txt
      - run:
          name: Run Tests
          command: python3 -m unittest --verbose
      - run:
          name: Check Types - Pyre
          command: pyre check
      - run:
          name: Check Types - Mypy
          command: mypy .
      - run:
          name: Check Lint - Flake8
          command: flake8
      - run:
          name: Check Format - Black
          command: black --check .